# Generated by Django 2.1.7 on 2019-03-13 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_category',
            new_name='bookcategory',
        ),
    ]
