# Generated by Django 2.1.7 on 2019-03-15 00:57
import csv
import os.path

from django.db import migrations
from django.conf import settings

def load_book_data(apps, schema_editor):
    Book = apps.get_model('book_shelf', 'Book')
    Category = apps.get_model('book_shelf', 'Category')
    Author = apps.get_model('book_shelf', 'Author')

    datapath = os.path.join(settings.BASE_DIR, 'uploads')
    datafile = os.path.join(datapath, 'list_of_books.csv')

    Book.objects.all().delete()
    Category.objects.all().delete()
    Author.objects.all().delete()
    with open(datafile, encoding = "ISO-8859-1") as file:
        reader = csv.DictReader(file)

        for row in reader:
            if row['category']:
                category, _ = Category.objects.get_or_create(category=row['category'])
            
            category.save()

            if row['author']:
                author, _ = Author.objects.get_or_create(author=row['author'])

            book = Book(
                title = row['title'],
                summary = row['summary'],
                book_url = row['book_url'],
                author=author,
            )

            book.save()

            book.category.add(category)

class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0002_auto_20190314_2137'),
    ]

    operations = [
        migrations.RunPython(load_book_data)
    ]