# Generated by Django 2.1.7 on 2019-03-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0003_add_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
