# Generated by Django 2.1.7 on 2019-03-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0004_auto_20190315_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
