# Generated by Django 2.1.7 on 2019-03-17 16:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_shelf', '0004_auto_20190317_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='category', unique=True),
        ),
    ]
